Add docs for 'OptionalValidatingQueryParamDecoderMatcher'.
http4s/http4s pull request #3710
Opened 2020-09-24 18:24 UTC by kevinmeredith

2020-09-24 21:30 UTC, ChristopherDavenport requested changes
This is after the link table and should be placed before the link table.

2020-09-24 21:32 UTC, kevinmeredith commented
Hi @ChristopherDavenport - thanks for reviewing. You're talking about how my changes are after https://github.com/http4s/http4s/pull/3710/files#diff-f5604df42f3b16985fefa40783ef823cR519? 

Please say more since I'm not sure how to address your comment.

2020-09-25 03:10 UTC, kevinmeredith commented
Perhaps https://github.com/http4s/http4s/pull/3710/commits/746ec8b833958a829ef88c21db92af8a638420b4 addresses your comment, @ChristopherDavenport?

2020-09-25 04:52 UTC, ChristopherDavenport approved these changes

2020-09-25 07:00 UTC, merged