Move connmanager
http4s/http4s pull request #4747
Opened 2021-04-14 19:36 UTC by vasilmkd

Resolves #4712.

The second commit in this PR might be controversial. I made all of the moved classes private, including some of the classes extending exceptions. I'd like some opinions on this.

Furthermore, I just dropped the `WaitQueueTimeoutException` class in `package.scala` under `client`. It is used by the `Retry` middleware. Not sure if it needs to be in a separate file.

2021-04-25 03:55 UTC, rossabaker requested changes
I like making the classes private.  I don't like making the exceptions private.

Otherwise, looks great.

2021-04-25 08:57 UTC, vasilmkd commented
Ah, sorry, I totally forgot about this one. Fixing.

2021-04-25 22:45 UTC, vasilmkd commented on blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala
> +private final case class WaitQueueFullFailure() extends RuntimeException {
Done.

2021-04-25 22:45 UTC, vasilmkd commented
Sorry for delaying this unnecessarily.

2021-04-25 23:15 UTC, vasilmkd commented
I think the failing test is unrelated to the changes. It passed for me locally.

2021-04-26 00:26 UTC, rossabaker approved these changes

2021-04-26 00:26 UTC, merged