Refactor some `Http1Connection` methods
http4s/http4s pull request #5789
Opened 2021-12-26 14:55 UTC by danicheg

This refactors some methods of the `Http1Connection` to simplify reasoning. Implementation, by and large, wasn't changed. Just decomposition was made more fine-grained and nested ifs replaced by pattern-matching.

2021-12-30 15:21 UTC, RafalSumislawski requested changes

2021-12-30 15:21 UTC, RafalSumislawski commented on blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
> +  private def terminationConditionParsingPrelude(): Either[Throwable, Option[Chunk[Byte]]] =
I would like to search for a better name for this method. It actually is relevant to parsing the body not the prelude. It's called when an EOF is received while parsing body, and the purpose of this metod it to decide whether it's ok that we recieved the EOF or not.

Maybe something like `onEofWhileReadingBody`?

2021-12-30 15:21 UTC, RafalSumislawski commented on blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
> +  private def cleanupParsingPrelude(closeOnFinish: Boolean, headers: Headers): Unit =
Maybe `cleanupParsingResponse`? Similarly to my comment on `terminationConditionParsingPrelude`. The `cleanupParsingPrelude` happens later than after parsing prelude. First we parse the prelude, then the body, then (optionally) the trailers and then we clean up.

IMO it should be `cleanUp` (a verb) not `cleanup` (a noun).

2021-12-30 15:21 UTC, RafalSumislawski commented on blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
> +  private def parsePrelude(
IMO this class would be easier if reading it top to bottom would be consistent with the order in which these operations happen (methods are called). The already existing methods are ordered like this. At least the most important ones.

I would like to see them in this order:
- runRequest
- executeRequest
- receiveResponse
- handleRead
- parsePrelude
- parsePreludeFinished (new)
- terminationConditionParsingPrelude (new)
- cleanupParsingPrelude (new)

2022-01-04 11:36 UTC, danicheg commented
@RafalSumislawski wow, what an utter review! :) If I get it right, you argue on most about naming, formatting, and order of methods. I give or take ok with your concerns, so feel free to proceed with my work on this if you want it. I'm not so interested in pushing this further.

2022-01-04 11:38 UTC, danicheg commented on blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
> +    try if (!parser.finishedResponseLine(buffer))
Probably this should be done by Scalafmt? Though it's not looking so bizarre for me.

2022-01-06 16:25 UTC, RafalSumislawski approved these changes

2022-01-06 16:26 UTC, RafalSumislawski commented
Hi @danicheg 
I applied the changes that I suggested earlier in the review. Please check if you're ok with the changes before we merge.

2022-01-07 13:18 UTC, danicheg commented
@RafalSumislawski thanks. LGTM.

2022-01-07 17:28 UTC, merged